title: 封神榜 - 吳淡如
description: 封神榜 - 吳淡如
time: Tue, 09 Apr 2024 00:15:24 +0000
items:
  - title: 00. 封神榜
    size: 1333577
    duration: 155
  - title: 01. 得罪女神就會天下大亂
    size: 7157159
    duration: 869
  - title: 02. 不當我岳父，就當我仇人
    size: 7534141
    duration: 901
  - title: 03. 妲己差點被自己爸爸殺掉
    size: 8251665
    duration: 1032
  - title: 04. 雲中子來京師殺狐狸精
    size: 7408476
    duration: 928
  - title: 05. 梅伯因勸諫被處炮烙之刑
    size: 7236055
    duration: 817
  - title: 06. 紂王處死皇后，追殺兒子
    size: 8274610
    duration: 943
  - title: 07. 連兒子都要殺！紂王的太子與弟弟的逃亡
    size: 8403785
    duration: 888
  - title: 08. 禍害鋪天蓋地，四大諸侯會有命嗎？
    size: 9094635
    duration: 929
  - title: 09. 占卜大王姬昌預測到自己的命運
    size: 8287359
    duration: 890
  - title: 10. 哪咤真是個磨人精
    size: 9581486
    duration: 983
  - title: 11. 爸媽總是很無奈！哪咤又射死仙人....
    size: 8379723
    duration: 973
  - title: 12. 哪咤連自己爸爸也追殺，誰來解圍？
    size: 9388441
    duration: 1043
  - title: 13. 姜子牙七十二歲下山
    size: 7961732
    duration: 900
  - title: 14. 琵琶精死於姜子牙之手
    size: 8104934
    duration: 904
  - title: 15. 姜子牙逃出朝歌又離婚
    size: 9091630
    duration: 997
  - title: 16. 伯邑考為了救父被做成肉餅
    size: 9004325
    duration: 1004
  - title: 17. 七歲雷震子認父與救父
    size: 8542998
    duration: 935
  - title: 18. 西伯侯姫昌歷經萬難回了家
    size: 8628136
    duration: 1019
  - title: 19. 肉餅變成三隻小兔子
    size: 8323474
    duration: 978
  - title: 20. 姜太公釣魚釣到西伯侯
    size: 8497716
    duration: 938
  - title: 21. 妲己的師弟師妹都被燒死
    size: 9337086
    duration: 1052
  - title: 22. 紂王多了新妃子，妲己怎麼這麼寬宏大量？
    size: 8096850
    duration: 942
  - title: 23. 姬昌與姜子牙出征
    size: 8370023
    duration: 955
  - title: 24. 姬發繼位，妲己陷害黃飛虎妻
    size: 8530878
    duration: 995
  - title: 25. 黃飛虎投奔西歧
    size: 8807322
    duration: 1047
  - title: 26. 黃飛虎過關斬將
    size: 9027470
    duration: 991
  - title: 27. 黃飛虎終於到了西歧
    size: 8408109
    duration: 980
  - title: 28. 聞太師討伐西歧
    size: 8051879
    duration: 967
  - title: 29. 姜子牙打不贏，上山求助
    size: 11267443
    duration: 1068
  - title: 30. 姜子牙拿到法寶救西歧
    size: 9118739
    duration: 1021
  - title: 31. 哪咤的兄弟都來助陣
    size: 8279999
    duration: 962
  - title: 32. 姜太公被困，全城皆傷兵
    size: 10054505
    duration: 973
  - title: 33. 聞太師親自出征姜子牙
    size: 7913600
    duration: 935
  - title: 34. 聞太師求救兵來了團神仙
    size: 8622549
    duration: 961
  - title: 35. 赤精子急救姜子牙魂魄
    size: 8301286
    duration: 970
  - title: 36. 十大絕陣好難破怎麼辦？
    size: 9480802
    duration: 1025
  - title: 37. 峨嵋山趙恭公明打死姜子牙
    size: 8610440
    duration: 990
  - title: 38. 燃燈道人也沒法招架的法寶
    size: 8776831
    duration: 981
  - title: 39. 十大絕陣破了九個
    size: 8831540
    duration: 1002
  - title: 40. 十二個仙人變成凡人
    size: 8494535
    duration: 939
  - title: 41. 十絕陣全破怎麼周武王死了
    size: 9595268
    duration: 1009
  - title: 42a. 聞太師兵敗潰逃
    size: 9378423
    duration: 980
  - title: 42b. 鄧九公出征哪咤被女將打傷
    size: 8970774
    duration: 976
  - title: 43. 土行孫為了娶親大展神通
    size: 8848268
    duration: 944
  - title: 44. 鄧九公為了女兒投降
    size: 11092582
    duration: 1162
  - title: 45. 想投降又不能如願的蘇護西征
    size: 9462222
    duration: 1002
  - title: 46. 遇到瘟神啦！
    size: 9021444
    duration: 968
  - title: 47. 紂王二皇子下山變叛徒
    size: 9264100
    duration: 1022
  - title: 48. 赤精子下山收拾徒弟
    size: 9725650
    duration: 1029
  - title: 49. 蘇護投降紂王又派張山來
    size: 8930092
    duration: 934
  - title: 50. 殷太子下山成為姜子牙敵人
    size: 9286790
    duration: 1011
  - title: 51. 殷郊被兩座山夾殺
    size: 8481264
    duration: 935
  - title: 52. 龍吉公主與月下老人
    size: 8790784
    duration: 945
  - title: 53. 姜子牙大舉東征朝歌
    size: 9343229
    duration: 1005
  - title: 54. 這些仙人都被怪光收走了
    size: 9150499
    duration: 994
  - title: 55. 姜子牙大破三山關向東挺進
    size: 8162684
    duration: 908
  - title: 56. 火靈聖母銳不可擋
    size: 8620550
    duration: 968
  - title: 57. 通天教主也糊塗了
    size: 9658914
    duration: 1070
  - title: 58. 來了一把難纏的化血神刀
    size: 7907547
    duration: 1075
  - title: 59. 好厲害的風車陣 
    size: 7433651
    duration: 1029
  - title: 60. 誅仙陣足以誅人仙人
    size: 7427514
    duration: 997
  - title: 61. 界牌關還是超難破
    size: 8850519
    duration: 963
  - title: 62. 又有一個怪陣出現了
    size: 8239644
    duration: 931
  - title: 63. 姜子牙陷瘟癀陣一百天
    size: 9751400
    duration: 1087
  - title: 64. 萬仙陣裡的怪物們
    size: 9357321
    duration: 1038
  - title: 65. 萬仙教中萬獸嚎
    size: 9492806
    duration: 1064
  - title: 66. 老子和通天教主師父來破萬仙陣
    size: 8880072
    duration: 1003
  - title: 67. 好兇險的臨潼關
    size: 8474978
    duration: 946
  - title: 68. 土行孫就這樣去了封神台
    size: 8366492
    duration: 999
  - title: 69. 三個千年妖精當統帥
    size: 8254898
    duration: 901
  - title: 70. 桃樹柳樹也來幫紂王
    size: 9145309
    duration: 1011
  - title: 71. 楊戩殺梅山七怪
    size: 9264941
    duration: 1040
  - title: 72. 東伯侯智取遊魂關
    size: 10885861
    duration: 1062
  - title: 73. 紂王自焚
    size: 8683308
    duration: 985
  - title: 74. 完結：是人是妖皆封神
    size: 11009947
    duration: 1230
